language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: WuIIrCLoywneHfr3CVIkih2Qh0sCDd4eMWDYvKEU28GKHT4ZCylTrCHvhpVmUK8wb7C1gmielW3fySAB+KOcr6kCN2IN5uq65puKazXt9Z+WtoKsI5CDbqgX46vko6jopRcCKmok+ZbdmCtA+dooaDjCamrAKFPwX9W1257l0RU=
